#include "pattern.h"
#include <iostream>
#include <vector>
#include <ctime>

// Open the file to write the pattern generated by me
void PATTERN::setupPatternFile()
{
	string str = "mkdir ";
	str.append(xstr(INDIR));
	system(str.c_str());                                    

	str = "./";
	str.append(xstr(INDIR));
	str.append("/");
	str.append(pattern_name);
	pattern_name = str;
	ofs.open(pattern_name.c_str(), ofstream::out | ofstream::trunc);   
	if(!ofs.is_open())                                                         
		std::cout << "Cannot open file!\n";
}

void PATTERN::initPattern()
{
	int i;

	no_pi_infile = inlist.size();

	for(i = 0; i < no_pi_infile; i++){
		ofs << "PI " << inlist[i]->GetName();
		if( i < no_pi_infile-1)
			ofs << " ";
	}
	ofs << endl;
}

void PATTERN::setPatterninput()
{
	int i;
	string str;

	patterninput.open(pattern_name.c_str(), ios::in);
	if(!patterninput){
		cout << "Unable to open pattern file" << endl;
		exit(-1);
	}

	for(i = 0; i < no_pi_infile*2; i++){
		patterninput >> str;
	}

}

void PATTERN::genRandomPattern(int pattern_number)
{
	setupPatternFile();
	initPattern();
	int i, j, random(0);
	
	srand(time(NULL));

	for(i = 0; i < pattern_number; i++){
		for(j = 0; j < no_pi_infile; j++){
			random = rand()%2;
			ofs << random;
		}
		ofs << endl;
	}
}

void PATTERN::genRandomPatternUnknown(int pattern_number)
{
	setupPatternFile();
	initPattern();

	int i, j, random(0);
	
	srand(time(NULL));

	for(i = 0; i < pattern_number; i++){
		for(j = 0; j < no_pi_infile; j++){
			random = rand()%3;
			if(random == 2)
				ofs << 'X';
			else
				ofs << random;
		}
		ofs << endl;
	}
}
