#include "pattern.h"
#include <iostream>
#include <vector>

// Open the file to write the pattern generated by me
void PATTERN::setupPatternFile()
{
	string str = "mkdir ";
	str.append(xstr(INDIR));
	system(str.c_str());                                    

	str = "./";
	str.append(xstr(INDIR));
	str.append("/");
	str.append(pattern_name);
	ofs.open(str.c_str(), ofstream::out | ofstream::trunc);   
	if(!ofs.is_open())                                                         
		std::cout << "Cannot open file!\n";
}

void PATTERN::printPatternHeader()
{
	vector<GATE*>::iterator it;

	for(it = inlist.begin(); it != inlist.end(); it++)
		ofs << "PI " << (*it)->GetName() << " ";

	ofs << endl;
}

void PATTERN::genRandomPattern(int pattern_number)
{
	setupPatternFile();
	printPatternHeader();
	//ofs << pattern_number;
}

void PATTERN::genRandomPatternUnknown(int pattern_number)
{
	setupPatternFile();
	//ofs << pattern_number;
}
